# version of docker compose we are using
version: "3.9"

# app - name of our service
# build -  run docker from root directory

services:
  recipe-app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./recipe-app:/recipe-app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"